.class public final Lkotlinx/coroutines/DispatchedKt;
.super Ljava/lang/Object;
.source "Dispatched.kt"


# annotations
.annotation system Ldalvik/annotation/SourceDebugExtension;
    value = "SMAP\nDispatched.kt\nKotlin\n*S Kotlin\n*F\n+ 1 Dispatched.kt\nkotlinx/coroutines/DispatchedKt\n+ 2 Dispatched.kt\nkotlinx/coroutines/DispatchedContinuation\n+ 3 CoroutineContext.kt\nkotlinx/coroutines/CoroutineContextKt\n*L\n1#1,328:1\n58#1,16:329\n65#1,10:345\n25#1,12:355\n58#1,16:367\n65#1,10:383\n37#1:393\n58#1,16:394\n65#1,10:410\n22#1,15:426\n58#1,3:441\n61#1,13:462\n65#1,10:475\n37#1:485\n22#1,15:496\n58#1,3:511\n326#1,2:536\n61#1,13:542\n65#1,10:555\n37#1:565\n326#1,2:568\n326#1,2:570\n326#1,2:572\n25#1,12:574\n58#1,16:586\n65#1,10:602\n37#1:612\n116#2,6:420\n122#2:444\n148#2,7:445\n123#2:452\n159#2:453\n160#2,2:457\n162#2:460\n125#2:461\n126#2,2:486\n131#2,8:488\n139#2,16:514\n140#2:530\n166#2:531\n167#2:535\n168#2:538\n169#2:540\n142#2:541\n143#2,2:566\n43#3,3:454\n47#3:459\n43#3,3:532\n47#3:539\n*E\n*S KotlinDebug\n*F\n+ 1 Dispatched.kt\nkotlinx/coroutines/DispatchedKt\n*L\n36#1,16:329\n36#1,10:345\n48#1,16:394\n48#1,10:410\n184#1,15:426\n184#1,3:441\n184#1,13:462\n184#1,10:475\n184#1:485\n189#1,15:496\n189#1,3:511\n189#1,2:536\n189#1,13:542\n189#1,10:555\n189#1:565\n190#1,2:568\n199#1,2:570\n200#1,2:572\n285#1,12:574\n285#1,16:586\n285#1,10:602\n285#1:612\n184#1,6:420\n184#1:444\n184#1,7:445\n184#1:452\n184#1:453\n184#1,2:457\n184#1:460\n184#1:461\n184#1,2:486\n189#1,8:488\n189#1,16:514\n189#1:530\n189#1:531\n189#1:535\n189#1:538\n189#1:540\n189#1:541\n189#1,2:566\n184#1,3:454\n184#1:459\n189#1,3:532\n189#1:539\n*E\n"
.end annotation

.annotation runtime Lkotlin/Metadata;
    bv = {
        0x1,
        0x0,
        0x3
    }
    d1 = {
        "\u0000N\n\u0000\n\u0002\u0018\u0002\n\u0002\u0008\u0003\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0008\n\u0000\n\u0002\u0010\u000b\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\u0008\u0002\n\u0002\u0018\u0002\n\u0002\u0008\u0002\n\u0002\u0018\u0002\n\u0002\u0008\u0006\n\u0002\u0010\u0003\n\u0002\u0008\u0006\n\u0002\u0018\u0002\n\u0002\u0008\u0002\u001a\"\u0010\u0004\u001a\u00020\u0005\"\u0004\u0008\u0000\u0010\u0006*\u0008\u0012\u0004\u0012\u0002H\u00060\u00072\u0008\u0008\u0002\u0010\u0008\u001a\u00020\tH\u0000\u001a;\u0010\n\u001a\u00020\u000b*\u0006\u0012\u0002\u0008\u00030\u000c2\u0008\u0010\r\u001a\u0004\u0018\u00010\u000e2\u0006\u0010\u0008\u001a\u00020\t2\u0008\u0008\u0002\u0010\u000f\u001a\u00020\u000b2\u000c\u0010\u0010\u001a\u0008\u0012\u0004\u0012\u00020\u00050\u0011H\u0082\u0008\u001a.\u0010\u0012\u001a\u00020\u0005\"\u0004\u0008\u0000\u0010\u0006*\u0008\u0012\u0004\u0012\u0002H\u00060\u00072\u000c\u0010\u0013\u001a\u0008\u0012\u0004\u0012\u0002H\u00060\u00142\u0006\u0010\u0015\u001a\u00020\tH\u0000\u001a%\u0010\u0016\u001a\u00020\u0005\"\u0004\u0008\u0000\u0010\u0006*\u0008\u0012\u0004\u0012\u0002H\u00060\u00142\u0006\u0010\u0017\u001a\u0002H\u0006H\u0000\u00a2\u0006\u0002\u0010\u0018\u001a \u0010\u0019\u001a\u00020\u0005\"\u0004\u0008\u0000\u0010\u0006*\u0008\u0012\u0004\u0012\u0002H\u00060\u00142\u0006\u0010\u001a\u001a\u00020\u001bH\u0000\u001a%\u0010\u001c\u001a\u00020\u0005\"\u0004\u0008\u0000\u0010\u0006*\u0008\u0012\u0004\u0012\u0002H\u00060\u00142\u0006\u0010\u0017\u001a\u0002H\u0006H\u0000\u00a2\u0006\u0002\u0010\u0018\u001a \u0010\u001d\u001a\u00020\u0005\"\u0004\u0008\u0000\u0010\u0006*\u0008\u0012\u0004\u0012\u0002H\u00060\u00142\u0006\u0010\u001a\u001a\u00020\u001bH\u0000\u001a\u0010\u0010\u001e\u001a\u00020\u0005*\u0006\u0012\u0002\u0008\u00030\u0007H\u0002\u001a\u0019\u0010\u001f\u001a\u00020\u0005*\u0006\u0012\u0002\u0008\u00030\u00142\u0006\u0010\u001a\u001a\u00020\u001bH\u0080\u0008\u001a\'\u0010 \u001a\u00020\u0005*\u0006\u0012\u0002\u0008\u00030\u00072\u0006\u0010!\u001a\u00020\"2\u000c\u0010\u0010\u001a\u0008\u0012\u0004\u0012\u00020\u00050\u0011H\u0082\u0008\u001a\u0012\u0010#\u001a\u00020\u000b*\u0008\u0012\u0004\u0012\u00020\u00050\u000cH\u0000\"\u0016\u0010\u0000\u001a\u00020\u00018\u0002X\u0083\u0004\u00a2\u0006\u0008\n\u0000\u0012\u0004\u0008\u0002\u0010\u0003\u00a8\u0006$"
    }
    d2 = {
        "UNDEFINED",
        "Lkotlinx/coroutines/internal/Symbol;",
        "UNDEFINED$annotations",
        "()V",
        "dispatch",
        "",
        "T",
        "Lkotlinx/coroutines/DispatchedTask;",
        "mode",
        "",
        "executeUnconfined",
        "",
        "Lkotlinx/coroutines/DispatchedContinuation;",
        "contState",
        "",
        "doYield",
        "block",
        "Lkotlin/Function0;",
        "resume",
        "delegate",
        "Lkotlin/coroutines/Continuation;",
        "useMode",
        "resumeCancellable",
        "value",
        "(Lkotlin/coroutines/Continuation;Ljava/lang/Object;)V",
        "resumeCancellableWithException",
        "exception",
        "",
        "resumeDirect",
        "resumeDirectWithException",
        "resumeUnconfined",
        "resumeWithStackTrace",
        "runUnconfinedEventLoop",
        "eventLoop",
        "Lkotlinx/coroutines/EventLoop;",
        "yieldUndispatched",
        "kotlinx-coroutines-core"
    }
    k = 0x2
    mv = {
        0x1,
        0x1,
        0xf
    }
.end annotation


# static fields
.field private static final UNDEFINED:Lkotlinx/coroutines/internal/Symbol;


# direct methods
.method static constructor <clinit>()V
    .locals 2

    .line 13
    new-instance v0, Lkotlinx/coroutines/internal/Symbol;

    const-string v1, "UNDEFINED"

    invoke-direct {v0, v1}, Lkotlinx/coroutines/internal/Symbol;-><init>(Ljava/lang/String;)V

    sput-object v0, Lkotlinx/coroutines/DispatchedKt;->UNDEFINED:Lkotlinx/coroutines/internal/Symbol;

    return-void
.end method

.method private static synthetic UNDEFINED$annotations()V
    .locals 0

    return-void
.end method

.method public static final synthetic access$getUNDEFINED$p()Lkotlinx/coroutines/internal/Symbol;
    .locals 1

    .line 1
    sget-object v0, Lkotlinx/coroutines/DispatchedKt;->UNDEFINED:Lkotlinx/coroutines/internal/Symbol;

    return-object v0
.end method

.method public static final synthetic access$runUnconfinedEventLoop(Lkotlinx/coroutines/DispatchedTask;Lkotlinx/coroutines/EventLoop;Lkotlin/jvm/functions/Function0;)V
    .locals 0
    .param p0, "$this$access_u24runUnconfinedEventLoop"    # Lkotlinx/coroutines/DispatchedTask;
    .param p1, "eventLoop"    # Lkotlinx/coroutines/EventLoop;
    .param p2, "block"    # Lkotlin/jvm/functions/Function0;

    .line 1
    invoke-static {p0, p1, p2}, Lkotlinx/coroutines/DispatchedKt;->runUnconfinedEventLoop(Lkotlinx/coroutines/DispatchedTask;Lkotlinx/coroutines/EventLoop;Lkotlin/jvm/functions/Function0;)V

    return-void
.end method

.method public static final dispatch(Lkotlinx/coroutines/DispatchedTask;I)V
    .locals 4
    .param p0, "$this$dispatch"    # Lkotlinx/coroutines/DispatchedTask;
    .param p1, "mode"    # I
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlinx/coroutines/DispatchedTask<",
            "-TT;>;I)V"
        }
    .end annotation

    const-string v0, "$this$dispatch"

    invoke-static {p0, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 290
    invoke-virtual {p0}, Lkotlinx/coroutines/DispatchedTask;->getDelegate$kotlinx_coroutines_core()Lkotlin/coroutines/Continuation;

    move-result-object v0

    .line 291
    .local v0, "delegate":Lkotlin/coroutines/Continuation;
    invoke-static {p1}, Lkotlinx/coroutines/ResumeModeKt;->isDispatchedMode(I)Z

    move-result v1

    if-eqz v1, :cond_1

    instance-of v1, v0, Lkotlinx/coroutines/DispatchedContinuation;

    if-eqz v1, :cond_1

    invoke-static {p1}, Lkotlinx/coroutines/ResumeModeKt;->isCancellableMode(I)Z

    move-result v1

    iget v2, p0, Lkotlinx/coroutines/DispatchedTask;->resumeMode:I

    invoke-static {v2}, Lkotlinx/coroutines/ResumeModeKt;->isCancellableMode(I)Z

    move-result v2

    if-ne v1, v2, :cond_1

    .line 293
    move-object v1, v0

    check-cast v1, Lkotlinx/coroutines/DispatchedContinuation;

    iget-object v1, v1, Lkotlinx/coroutines/DispatchedContinuation;->dispatcher:Lkotlinx/coroutines/CoroutineDispatcher;

    .line 294
    .local v1, "dispatcher":Lkotlinx/coroutines/CoroutineDispatcher;
    invoke-interface {v0}, Lkotlin/coroutines/Continuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v2

    .line 295
    .local v2, "context":Lkotlin/coroutines/CoroutineContext;
    invoke-virtual {v1, v2}, Lkotlinx/coroutines/CoroutineDispatcher;->isDispatchNeeded(Lkotlin/coroutines/CoroutineContext;)Z

    move-result v3

    if-eqz v3, :cond_0

    .line 296
    move-object v3, p0

    check-cast v3, Ljava/lang/Runnable;

    invoke-virtual {v1, v2, v3}, Lkotlinx/coroutines/CoroutineDispatcher;->dispatch(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Runnable;)V

    goto :goto_0

    .line 298
    :cond_0
    invoke-static {p0}, Lkotlinx/coroutines/DispatchedKt;->resumeUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    .line 299
    .end local v1    # "dispatcher":Lkotlinx/coroutines/CoroutineDispatcher;
    .end local v2    # "context":Lkotlin/coroutines/CoroutineContext;
    goto :goto_0

    .line 301
    :cond_1
    invoke-static {p0, v0, p1}, Lkotlinx/coroutines/DispatchedKt;->resume(Lkotlinx/coroutines/DispatchedTask;Lkotlin/coroutines/Continuation;I)V

    .line 302
    :goto_0
    nop

    .line 303
    return-void
.end method

.method public static synthetic dispatch$default(Lkotlinx/coroutines/DispatchedTask;IILjava/lang/Object;)V
    .locals 0

    const/4 p3, 0x1

    and-int/2addr p2, p3

    if-eqz p2, :cond_0

    .line 289
    const/4 p1, 0x1

    :cond_0
    invoke-static {p0, p1}, Lkotlinx/coroutines/DispatchedKt;->dispatch(Lkotlinx/coroutines/DispatchedTask;I)V

    return-void
.end method

.method private static final executeUnconfined(Lkotlinx/coroutines/DispatchedContinuation;Ljava/lang/Object;IZLkotlin/jvm/functions/Function0;)Z
    .locals 8
    .param p0, "$this$executeUnconfined"    # Lkotlinx/coroutines/DispatchedContinuation;
    .param p1, "contState"    # Ljava/lang/Object;
    .param p2, "mode"    # I
    .param p3, "doYield"    # Z
    .param p4, "block"    # Lkotlin/jvm/functions/Function0;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lkotlinx/coroutines/DispatchedContinuation<",
            "*>;",
            "Ljava/lang/Object;",
            "IZ",
            "Lkotlin/jvm/functions/Function0<",
            "Lkotlin/Unit;",
            ">;)Z"
        }
    .end annotation

    const/4 v0, 0x0

    .line 25
    .local v0, "$i$f$executeUnconfined":I
    sget-object v1, Lkotlinx/coroutines/ThreadLocalEventLoop;->INSTANCE:Lkotlinx/coroutines/ThreadLocalEventLoop;

    invoke-virtual {v1}, Lkotlinx/coroutines/ThreadLocalEventLoop;->getEventLoop$kotlinx_coroutines_core()Lkotlinx/coroutines/EventLoop;

    move-result-object v1

    .line 27
    .local v1, "eventLoop":Lkotlinx/coroutines/EventLoop;
    const/4 v2, 0x0

    if-eqz p3, :cond_0

    invoke-virtual {v1}, Lkotlinx/coroutines/EventLoop;->isUnconfinedQueueEmpty()Z

    move-result v3

    if-eqz v3, :cond_0

    return v2

    .line 28
    :cond_0
    invoke-virtual {v1}, Lkotlinx/coroutines/EventLoop;->isUnconfinedLoopActive()Z

    move-result v3

    const/4 v4, 0x1

    if-eqz v3, :cond_1

    .line 30
    iput-object p1, p0, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 31
    iput p2, p0, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 32
    move-object v2, p0

    check-cast v2, Lkotlinx/coroutines/DispatchedTask;

    invoke-virtual {v1, v2}, Lkotlinx/coroutines/EventLoop;->dispatchUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    .line 33
    const/4 v2, 0x1

    goto :goto_2

    .line 36
    :cond_1
    move-object v3, p0

    check-cast v3, Lkotlinx/coroutines/DispatchedTask;

    .local v3, "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    const/4 v5, 0x0

    .line 329
    .local v5, "$i$f$runUnconfinedEventLoop":I
    invoke-virtual {v1, v4}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 330
    nop

    .line 331
    :try_start_0
    invoke-interface {p4}, Lkotlin/jvm/functions/Function0;->invoke()Ljava/lang/Object;

    .line 332
    :goto_0
    nop

    .line 334
    invoke-virtual {v1}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v6
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    if-nez v6, :cond_2

    .line 332
    invoke-static {v4}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    goto :goto_1

    :cond_2
    goto :goto_0

    .line 345
    :catchall_0
    move-exception v6

    .line 350
    .local v6, "e$iv":Ljava/lang/Throwable;
    const/4 v7, 0x0

    :try_start_1
    invoke-virtual {v3, v6, v7}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_1

    .end local v6    # "e$iv":Ljava/lang/Throwable;
    invoke-static {v4}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    .line 343
    :goto_1
    invoke-virtual {v1, v4}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    invoke-static {v4}, Lkotlin/jvm/internal/InlineMarker;->finallyEnd(I)V

    .line 344
    nop

    .line 354
    nop

    .line 37
    .end local v3    # "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v5    # "$i$f$runUnconfinedEventLoop":I
    nop

    .line 28
    :goto_2
    return v2

    .line 344
    .restart local v3    # "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v5    # "$i$f$runUnconfinedEventLoop":I
    :catchall_1
    move-exception v2

    invoke-static {v4}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    .line 343
    invoke-virtual {v1, v4}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    invoke-static {v4}, Lkotlin/jvm/internal/InlineMarker;->finallyEnd(I)V

    throw v2
.end method

.method static synthetic executeUnconfined$default(Lkotlinx/coroutines/DispatchedContinuation;Ljava/lang/Object;IZLkotlin/jvm/functions/Function0;ILjava/lang/Object;)Z
    .locals 6
    .param p0, "$this$executeUnconfined"    # Lkotlinx/coroutines/DispatchedContinuation;
    .param p1, "contState"    # Ljava/lang/Object;
    .param p2, "mode"    # I
    .param p3, "doYield"    # Z
    .param p4, "block"    # Lkotlin/jvm/functions/Function0;

    and-int/lit8 p5, p5, 0x4

    if-eqz p5, :cond_0

    .line 22
    const/4 p3, 0x0

    :cond_0
    const/4 p5, 0x0

    .line 355
    .local p5, "$i$f$executeUnconfined":I
    sget-object p6, Lkotlinx/coroutines/ThreadLocalEventLoop;->INSTANCE:Lkotlinx/coroutines/ThreadLocalEventLoop;

    invoke-virtual {p6}, Lkotlinx/coroutines/ThreadLocalEventLoop;->getEventLoop$kotlinx_coroutines_core()Lkotlinx/coroutines/EventLoop;

    move-result-object p6

    .line 357
    .local p6, "eventLoop":Lkotlinx/coroutines/EventLoop;
    const/4 v0, 0x0

    if-eqz p3, :cond_1

    invoke-virtual {p6}, Lkotlinx/coroutines/EventLoop;->isUnconfinedQueueEmpty()Z

    move-result v1

    if-eqz v1, :cond_1

    return v0

    .line 358
    :cond_1
    invoke-virtual {p6}, Lkotlinx/coroutines/EventLoop;->isUnconfinedLoopActive()Z

    move-result v1

    const/4 v2, 0x1

    if-eqz v1, :cond_2

    .line 360
    iput-object p1, p0, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 361
    iput p2, p0, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 362
    move-object v0, p0

    check-cast v0, Lkotlinx/coroutines/DispatchedTask;

    invoke-virtual {p6, v0}, Lkotlinx/coroutines/EventLoop;->dispatchUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    .line 363
    const/4 v0, 0x1

    goto :goto_2

    .line 366
    :cond_2
    move-object v1, p0

    check-cast v1, Lkotlinx/coroutines/DispatchedTask;

    .local v1, "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    const/4 v3, 0x0

    .line 367
    .local v3, "$i$f$runUnconfinedEventLoop":I
    invoke-virtual {p6, v2}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 368
    nop

    .line 369
    :try_start_0
    invoke-interface {p4}, Lkotlin/jvm/functions/Function0;->invoke()Ljava/lang/Object;

    .line 370
    :goto_0
    nop

    .line 372
    invoke-virtual {p6}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v4
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    if-nez v4, :cond_3

    .line 370
    invoke-static {v2}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    goto :goto_1

    :cond_3
    goto :goto_0

    .line 383
    :catchall_0
    move-exception v4

    .line 388
    .local v4, "e$iv":Ljava/lang/Throwable;
    const/4 v5, 0x0

    :try_start_1
    invoke-virtual {v1, v4, v5}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_1

    .end local v4    # "e$iv":Ljava/lang/Throwable;
    invoke-static {v2}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    .line 381
    :goto_1
    invoke-virtual {p6, v2}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    invoke-static {v2}, Lkotlin/jvm/internal/InlineMarker;->finallyEnd(I)V

    .line 382
    nop

    .line 392
    nop

    .line 393
    .end local v1    # "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v3    # "$i$f$runUnconfinedEventLoop":I
    nop

    .line 358
    :goto_2
    return v0

    .line 382
    .restart local v1    # "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v3    # "$i$f$runUnconfinedEventLoop":I
    :catchall_1
    move-exception v0

    invoke-static {v2}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    .line 381
    invoke-virtual {p6, v2}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    invoke-static {v2}, Lkotlin/jvm/internal/InlineMarker;->finallyEnd(I)V

    throw v0
.end method

.method public static final resume(Lkotlinx/coroutines/DispatchedTask;Lkotlin/coroutines/Continuation;I)V
    .locals 3
    .param p0, "$this$resume"    # Lkotlinx/coroutines/DispatchedTask;
    .param p1, "delegate"    # Lkotlin/coroutines/Continuation;
    .param p2, "useMode"    # I
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlinx/coroutines/DispatchedTask<",
            "-TT;>;",
            "Lkotlin/coroutines/Continuation<",
            "-TT;>;I)V"
        }
    .end annotation

    const-string v0, "$this$resume"

    invoke-static {p0, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v0, "delegate"

    invoke-static {p1, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 307
    invoke-virtual {p0}, Lkotlinx/coroutines/DispatchedTask;->takeState$kotlinx_coroutines_core()Ljava/lang/Object;

    move-result-object v0

    .line 308
    .local v0, "state":Ljava/lang/Object;
    invoke-virtual {p0, v0}, Lkotlinx/coroutines/DispatchedTask;->getExceptionalResult$kotlinx_coroutines_core(Ljava/lang/Object;)Ljava/lang/Throwable;

    move-result-object v1

    .line 309
    .local v1, "exception":Ljava/lang/Throwable;
    if-eqz v1, :cond_1

    .line 316
    instance-of v2, p1, Lkotlinx/coroutines/DispatchedTask;

    if-eqz v2, :cond_0

    move-object v2, v1

    goto :goto_0

    :cond_0
    invoke-static {v1, p1}, Lkotlinx/coroutines/internal/StackTraceRecoveryKt;->recoverStackTrace(Ljava/lang/Throwable;Lkotlin/coroutines/Continuation;)Ljava/lang/Throwable;

    move-result-object v2

    .line 317
    .local v2, "recovered":Ljava/lang/Throwable;
    :goto_0
    invoke-static {p1, v2, p2}, Lkotlinx/coroutines/ResumeModeKt;->resumeWithExceptionMode(Lkotlin/coroutines/Continuation;Ljava/lang/Throwable;I)V

    .end local v2    # "recovered":Ljava/lang/Throwable;
    goto :goto_1

    .line 319
    :cond_1
    invoke-virtual {p0, v0}, Lkotlinx/coroutines/DispatchedTask;->getSuccessfulResult$kotlinx_coroutines_core(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v2

    invoke-static {p1, v2, p2}, Lkotlinx/coroutines/ResumeModeKt;->resumeMode(Lkotlin/coroutines/Continuation;Ljava/lang/Object;I)V

    .line 320
    :goto_1
    nop

    .line 321
    return-void
.end method

.method public static final resumeCancellable(Lkotlin/coroutines/Continuation;Ljava/lang/Object;)V
    .locals 21
    .param p0, "$this$resumeCancellable"    # Lkotlin/coroutines/Continuation;
    .param p1, "value"    # Ljava/lang/Object;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlin/coroutines/Continuation<",
            "-TT;>;TT;)V"
        }
    .end annotation

    move-object/from16 v1, p0

    move-object/from16 v2, p1

    const-string v0, "$this$resumeCancellable"

    invoke-static {v1, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 183
    nop

    .line 184
    instance-of v0, v1, Lkotlinx/coroutines/DispatchedContinuation;

    if-eqz v0, :cond_5

    move-object v3, v1

    check-cast v3, Lkotlinx/coroutines/DispatchedContinuation;

    .local v3, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v4, 0x0

    .line 420
    .local v4, "$i$f$resumeCancellable":I
    iget-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->dispatcher:Lkotlinx/coroutines/CoroutineDispatcher;

    invoke-virtual {v3}, Lkotlinx/coroutines/DispatchedContinuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v5

    invoke-virtual {v0, v5}, Lkotlinx/coroutines/CoroutineDispatcher;->isDispatchNeeded(Lkotlin/coroutines/CoroutineContext;)Z

    move-result v0

    const/4 v5, 0x1

    if-eqz v0, :cond_0

    .line 421
    iput-object v2, v3, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 422
    iput v5, v3, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 423
    iget-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->dispatcher:Lkotlinx/coroutines/CoroutineDispatcher;

    invoke-virtual {v3}, Lkotlinx/coroutines/DispatchedContinuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v5

    move-object v6, v3

    check-cast v6, Ljava/lang/Runnable;

    invoke-virtual {v0, v5, v6}, Lkotlinx/coroutines/CoroutineDispatcher;->dispatch(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Runnable;)V

    goto/16 :goto_7

    .line 425
    :cond_0
    const/4 v6, 0x1

    .local v6, "mode$iv$iv":I
    move-object v7, v3

    .line 426
    .local v7, "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v8, 0x0

    .local v8, "doYield$iv$iv":Z
    const/4 v9, 0x0

    .line 429
    .local v9, "$i$f$executeUnconfined":I
    sget-object v0, Lkotlinx/coroutines/ThreadLocalEventLoop;->INSTANCE:Lkotlinx/coroutines/ThreadLocalEventLoop;

    invoke-virtual {v0}, Lkotlinx/coroutines/ThreadLocalEventLoop;->getEventLoop$kotlinx_coroutines_core()Lkotlinx/coroutines/EventLoop;

    move-result-object v10

    .line 431
    .local v10, "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    nop

    .line 432
    invoke-virtual {v10}, Lkotlinx/coroutines/EventLoop;->isUnconfinedLoopActive()Z

    move-result v0

    if-eqz v0, :cond_1

    .line 434
    iput-object v2, v7, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 435
    iput v6, v7, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 436
    move-object v0, v7

    check-cast v0, Lkotlinx/coroutines/DispatchedTask;

    invoke-virtual {v10, v0}, Lkotlinx/coroutines/EventLoop;->dispatchUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    .line 437
    move-object/from16 v18, v3

    goto/16 :goto_6

    .line 440
    :cond_1
    move-object v11, v7

    check-cast v11, Lkotlinx/coroutines/DispatchedTask;

    .local v11, "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    const/4 v12, 0x0

    .line 441
    .local v12, "$i$f$runUnconfinedEventLoop":I
    invoke-virtual {v10, v5}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 442
    nop

    .line 443
    const/4 v13, 0x0

    .line 444
    .local v13, "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellable$1$iv":I
    move-object v0, v3

    .local v0, "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v14, 0x0

    .line 445
    .local v14, "$i$f$resumeCancelled":I
    :try_start_0
    invoke-virtual {v0}, Lkotlinx/coroutines/DispatchedContinuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v15

    sget-object v16, Lkotlinx/coroutines/Job;->Key:Lkotlinx/coroutines/Job$Key;

    move-object/from16 v5, v16

    check-cast v5, Lkotlin/coroutines/CoroutineContext$Key;

    invoke-interface {v15, v5}, Lkotlin/coroutines/CoroutineContext;->get(Lkotlin/coroutines/CoroutineContext$Key;)Lkotlin/coroutines/CoroutineContext$Element;

    move-result-object v5

    check-cast v5, Lkotlinx/coroutines/Job;
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_4

    .line 446
    .local v5, "job$iv$iv":Lkotlinx/coroutines/Job;
    if-eqz v5, :cond_2

    :try_start_1
    invoke-interface {v5}, Lkotlinx/coroutines/Job;->isActive()Z

    move-result v15

    if-nez v15, :cond_2

    .line 447
    invoke-interface {v5}, Lkotlinx/coroutines/Job;->getCancellationException()Ljava/util/concurrent/CancellationException;

    move-result-object v15

    check-cast v15, Ljava/lang/Throwable;

    sget-object v16, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {v15}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v15

    invoke-static {v15}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v15

    invoke-interface {v0, v15}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_0

    .line 448
    const/4 v15, 0x1

    goto :goto_0

    .line 475
    .end local v0    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v5    # "job$iv$iv":Lkotlinx/coroutines/Job;
    .end local v13    # "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellable$1$iv":I
    .end local v14    # "$i$f$resumeCancelled":I
    :catchall_0
    move-exception v0

    move-object/from16 v18, v3

    goto :goto_4

    .line 451
    .restart local v0    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v5    # "job$iv$iv":Lkotlinx/coroutines/Job;
    .restart local v13    # "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellable$1$iv":I
    .restart local v14    # "$i$f$resumeCancelled":I
    :cond_2
    const/4 v15, 0x0

    .end local v0    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v5    # "job$iv$iv":Lkotlinx/coroutines/Job;
    .end local v14    # "$i$f$resumeCancelled":I
    :goto_0
    if-nez v15, :cond_3

    .line 452
    move-object/from16 v5, p1

    .local v5, "value$iv$iv":Ljava/lang/Object;
    move-object v14, v3

    .local v14, "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v15, 0x0

    .line 453
    .local v15, "$i$f$resumeUndispatched":I
    :try_start_2
    invoke-virtual {v14}, Lkotlinx/coroutines/DispatchedContinuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v0

    iget-object v2, v14, Lkotlinx/coroutines/DispatchedContinuation;->countOrElement:Ljava/lang/Object;
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_4

    .local v2, "countOrElement$iv$iv$iv":Ljava/lang/Object;
    move-object/from16 v16, v0

    .local v16, "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    const/16 v17, 0x0

    .line 454
    .local v17, "$i$f$withCoroutineContext":I
    move-object/from16 v18, v3

    move-object/from16 v3, v16

    .end local v16    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .local v3, "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .local v18, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :try_start_3
    invoke-static {v3, v2}, Lkotlinx/coroutines/internal/ThreadContextKt;->updateThreadContext(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_3

    move-object/from16 v16, v0

    .line 455
    .local v16, "oldValue$iv$iv$iv":Ljava/lang/Object;
    nop

    .line 456
    const/4 v0, 0x0

    .line 457
    .local v0, "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatched$1$iv$iv":I
    move/from16 v19, v0

    .end local v0    # "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatched$1$iv$iv":I
    .local v19, "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatched$1$iv$iv":I
    :try_start_4
    iget-object v0, v14, Lkotlinx/coroutines/DispatchedContinuation;->continuation:Lkotlin/coroutines/Continuation;

    sget-object v20, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;
    :try_end_4
    .catchall {:try_start_4 .. :try_end_4} :catchall_2

    move-object/from16 v20, v2

    .end local v2    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .local v20, "countOrElement$iv$iv$iv":Ljava/lang/Object;
    :try_start_5
    invoke-static {v5}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v2

    invoke-interface {v0, v2}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 458
    .end local v19    # "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatched$1$iv$iv":I
    sget-object v0, Lkotlin/Unit;->INSTANCE:Lkotlin/Unit;
    :try_end_5
    .catchall {:try_start_5 .. :try_end_5} :catchall_1

    .line 459
    move-object/from16 v2, v16

    .end local v16    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .local v2, "oldValue$iv$iv$iv":Ljava/lang/Object;
    :try_start_6
    invoke-static {v3, v2}, Lkotlinx/coroutines/internal/ThreadContextKt;->restoreThreadContext(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Object;)V

    .line 460
    .end local v2    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .end local v3    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .end local v17    # "$i$f$withCoroutineContext":I
    .end local v20    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    goto :goto_2

    .line 459
    .restart local v3    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .restart local v16    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .restart local v17    # "$i$f$withCoroutineContext":I
    .restart local v20    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    :catchall_1
    move-exception v0

    move-object/from16 v2, v16

    .end local v16    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .restart local v2    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    goto :goto_1

    .end local v20    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .local v2, "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .restart local v16    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    :catchall_2
    move-exception v0

    move-object/from16 v20, v2

    move-object/from16 v2, v16

    .end local v16    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .local v2, "oldValue$iv$iv$iv":Ljava/lang/Object;
    .restart local v20    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    :goto_1
    invoke-static {v3, v2}, Lkotlinx/coroutines/internal/ThreadContextKt;->restoreThreadContext(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Object;)V

    .end local v4    # "$i$f$resumeCancellable":I
    .end local v6    # "mode$iv$iv":I
    .end local v7    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v8    # "doYield$iv$iv":Z
    .end local v9    # "$i$f$executeUnconfined":I
    .end local v10    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .end local v11    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v12    # "$i$f$runUnconfinedEventLoop":I
    .end local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local p0    # "$this$resumeCancellable":Lkotlin/coroutines/Continuation;
    .end local p1    # "value":Ljava/lang/Object;
    throw v0

    .line 451
    .end local v2    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .end local v5    # "value$iv$iv":Ljava/lang/Object;
    .end local v14    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v15    # "$i$f$resumeUndispatched":I
    .end local v17    # "$i$f$withCoroutineContext":I
    .end local v20    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .local v3, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v4    # "$i$f$resumeCancellable":I
    .restart local v6    # "mode$iv$iv":I
    .restart local v7    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v8    # "doYield$iv$iv":Z
    .restart local v9    # "$i$f$executeUnconfined":I
    .restart local v10    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .restart local v11    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v12    # "$i$f$runUnconfinedEventLoop":I
    .restart local p0    # "$this$resumeCancellable":Lkotlin/coroutines/Continuation;
    .restart local p1    # "value":Ljava/lang/Object;
    :cond_3
    move-object/from16 v18, v3

    .line 461
    .end local v3    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_2
    nop

    .end local v13    # "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellable$1$iv":I
    nop

    .line 462
    :goto_3
    nop

    .line 464
    invoke-virtual {v10}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v0
    :try_end_6
    .catchall {:try_start_6 .. :try_end_6} :catchall_3

    if-nez v0, :cond_4

    goto :goto_5

    .line 462
    :cond_4
    goto :goto_3

    .line 475
    :catchall_3
    move-exception v0

    goto :goto_4

    .end local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v3    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :catchall_4
    move-exception v0

    move-object/from16 v18, v3

    .line 480
    .end local v3    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .local v0, "e$iv$iv$iv":Ljava/lang/Throwable;
    .restart local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_4
    const/4 v2, 0x0

    :try_start_7
    invoke-virtual {v11, v0, v2}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_7
    .catchall {:try_start_7 .. :try_end_7} :catchall_5

    .line 473
    .end local v0    # "e$iv$iv$iv":Ljava/lang/Throwable;
    :goto_5
    const/4 v2, 0x1

    invoke-virtual {v10, v2}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    .line 474
    nop

    .line 484
    nop

    .line 485
    .end local v11    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v12    # "$i$f$runUnconfinedEventLoop":I
    nop

    .line 432
    .end local v6    # "mode$iv$iv":I
    .end local v7    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v8    # "doYield$iv$iv":Z
    .end local v9    # "$i$f$executeUnconfined":I
    .end local v10    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    :goto_6
    nop

    .line 486
    .end local v4    # "$i$f$resumeCancellable":I
    .end local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_7
    nop

    .line 487
    goto :goto_8

    .line 474
    .restart local v4    # "$i$f$resumeCancellable":I
    .restart local v6    # "mode$iv$iv":I
    .restart local v7    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v8    # "doYield$iv$iv":Z
    .restart local v9    # "$i$f$executeUnconfined":I
    .restart local v10    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .restart local v11    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v12    # "$i$f$runUnconfinedEventLoop":I
    .restart local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :catchall_5
    move-exception v0

    move-object v2, v0

    .line 473
    const/4 v3, 0x1

    invoke-virtual {v10, v3}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    throw v2

    .line 185
    .end local v4    # "$i$f$resumeCancellable":I
    .end local v6    # "mode$iv$iv":I
    .end local v7    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v8    # "doYield$iv$iv":Z
    .end local v9    # "$i$f$executeUnconfined":I
    .end local v10    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .end local v11    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v12    # "$i$f$runUnconfinedEventLoop":I
    .end local v18    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :cond_5
    sget-object v0, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static/range {p1 .. p1}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    invoke-interface {v1, v0}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 186
    :goto_8
    return-void
.end method

.method public static final resumeCancellableWithException(Lkotlin/coroutines/Continuation;Ljava/lang/Throwable;)V
    .locals 27
    .param p0, "$this$resumeCancellableWithException"    # Lkotlin/coroutines/Continuation;
    .param p1, "exception"    # Ljava/lang/Throwable;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlin/coroutines/Continuation<",
            "-TT;>;",
            "Ljava/lang/Throwable;",
            ")V"
        }
    .end annotation

    move-object/from16 v1, p0

    move-object/from16 v2, p1

    const-string v0, "$this$resumeCancellableWithException"

    invoke-static {v1, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v0, "exception"

    invoke-static {v2, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 188
    nop

    .line 189
    instance-of v0, v1, Lkotlinx/coroutines/DispatchedContinuation;

    if-eqz v0, :cond_5

    move-object v3, v1

    check-cast v3, Lkotlinx/coroutines/DispatchedContinuation;

    .local v3, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v4, 0x0

    .line 488
    .local v4, "$i$f$resumeCancellableWithException":I
    iget-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->continuation:Lkotlin/coroutines/Continuation;

    invoke-interface {v0}, Lkotlin/coroutines/Continuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v5

    .line 489
    .local v5, "context$iv":Lkotlin/coroutines/CoroutineContext;
    new-instance v0, Lkotlinx/coroutines/CompletedExceptionally;

    const/4 v6, 0x0

    const/4 v7, 0x2

    const/4 v8, 0x0

    invoke-direct {v0, v2, v6, v7, v8}, Lkotlinx/coroutines/CompletedExceptionally;-><init>(Ljava/lang/Throwable;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V

    move-object v9, v0

    .line 490
    .local v9, "state$iv":Lkotlinx/coroutines/CompletedExceptionally;
    iget-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->dispatcher:Lkotlinx/coroutines/CoroutineDispatcher;

    invoke-virtual {v0, v5}, Lkotlinx/coroutines/CoroutineDispatcher;->isDispatchNeeded(Lkotlin/coroutines/CoroutineContext;)Z

    move-result v0

    const/4 v10, 0x1

    if-eqz v0, :cond_0

    .line 491
    new-instance v0, Lkotlinx/coroutines/CompletedExceptionally;

    invoke-direct {v0, v2, v6, v7, v8}, Lkotlinx/coroutines/CompletedExceptionally;-><init>(Ljava/lang/Throwable;ZILkotlin/jvm/internal/DefaultConstructorMarker;)V

    iput-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 492
    iput v10, v3, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 493
    iget-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->dispatcher:Lkotlinx/coroutines/CoroutineDispatcher;

    move-object v6, v3

    check-cast v6, Ljava/lang/Runnable;

    invoke-virtual {v0, v5, v6}, Lkotlinx/coroutines/CoroutineDispatcher;->dispatch(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Runnable;)V

    goto/16 :goto_7

    .line 495
    :cond_0
    const/4 v7, 0x1

    .local v7, "mode$iv$iv":I
    move-object v11, v3

    .line 496
    .local v11, "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v12, 0x0

    .local v12, "doYield$iv$iv":Z
    const/4 v13, 0x0

    .line 499
    .local v13, "$i$f$executeUnconfined":I
    sget-object v0, Lkotlinx/coroutines/ThreadLocalEventLoop;->INSTANCE:Lkotlinx/coroutines/ThreadLocalEventLoop;

    invoke-virtual {v0}, Lkotlinx/coroutines/ThreadLocalEventLoop;->getEventLoop$kotlinx_coroutines_core()Lkotlinx/coroutines/EventLoop;

    move-result-object v14

    .line 501
    .local v14, "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    nop

    .line 502
    invoke-virtual {v14}, Lkotlinx/coroutines/EventLoop;->isUnconfinedLoopActive()Z

    move-result v0

    if-eqz v0, :cond_1

    .line 504
    iput-object v9, v11, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 505
    iput v7, v11, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 506
    move-object v0, v11

    check-cast v0, Lkotlinx/coroutines/DispatchedTask;

    invoke-virtual {v14, v0}, Lkotlinx/coroutines/EventLoop;->dispatchUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    .line 507
    move-object/from16 v25, v3

    goto/16 :goto_6

    .line 510
    :cond_1
    move-object v15, v11

    check-cast v15, Lkotlinx/coroutines/DispatchedTask;

    .local v15, "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    const/16 v16, 0x0

    .line 511
    .local v16, "$i$f$runUnconfinedEventLoop":I
    invoke-virtual {v14, v10}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 512
    nop

    .line 513
    const/16 v17, 0x0

    .line 514
    .local v17, "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellableWithException$1$iv":I
    move-object v0, v3

    .local v0, "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/16 v18, 0x0

    .line 523
    .local v18, "$i$f$resumeCancelled":I
    :try_start_0
    invoke-virtual {v0}, Lkotlinx/coroutines/DispatchedContinuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v6

    sget-object v20, Lkotlinx/coroutines/Job;->Key:Lkotlinx/coroutines/Job$Key;

    move-object/from16 v8, v20

    check-cast v8, Lkotlin/coroutines/CoroutineContext$Key;

    invoke-interface {v6, v8}, Lkotlin/coroutines/CoroutineContext;->get(Lkotlin/coroutines/CoroutineContext$Key;)Lkotlin/coroutines/CoroutineContext$Element;

    move-result-object v6

    check-cast v6, Lkotlinx/coroutines/Job;
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_4

    .line 524
    .local v6, "job$iv$iv":Lkotlinx/coroutines/Job;
    if-eqz v6, :cond_2

    :try_start_1
    invoke-interface {v6}, Lkotlinx/coroutines/Job;->isActive()Z

    move-result v8

    if-nez v8, :cond_2

    .line 525
    invoke-interface {v6}, Lkotlinx/coroutines/Job;->getCancellationException()Ljava/util/concurrent/CancellationException;

    move-result-object v8

    check-cast v8, Ljava/lang/Throwable;

    sget-object v19, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {v8}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v8

    invoke-static {v8}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v8

    invoke-interface {v0, v8}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_0

    .line 526
    const/4 v6, 0x1

    goto :goto_0

    .line 555
    .end local v0    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v6    # "job$iv$iv":Lkotlinx/coroutines/Job;
    .end local v17    # "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellableWithException$1$iv":I
    .end local v18    # "$i$f$resumeCancelled":I
    :catchall_0
    move-exception v0

    move-object/from16 v25, v3

    goto/16 :goto_4

    .line 529
    .restart local v0    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v6    # "job$iv$iv":Lkotlinx/coroutines/Job;
    .restart local v17    # "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellableWithException$1$iv":I
    .restart local v18    # "$i$f$resumeCancelled":I
    :cond_2
    const/4 v6, 0x0

    .end local v0    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v6    # "job$iv$iv":Lkotlinx/coroutines/Job;
    .end local v18    # "$i$f$resumeCancelled":I
    :goto_0
    if-nez v6, :cond_3

    .line 530
    move-object/from16 v0, p1

    .local v0, "exception$iv$iv":Ljava/lang/Throwable;
    move-object v6, v3

    .local v6, "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    move-object v8, v0

    .end local v0    # "exception$iv$iv":Ljava/lang/Throwable;
    .local v8, "exception$iv$iv":Ljava/lang/Throwable;
    const/16 v18, 0x0

    .line 531
    .local v18, "$i$f$resumeUndispatchedWithException":I
    :try_start_2
    invoke-virtual {v6}, Lkotlinx/coroutines/DispatchedContinuation;->getContext()Lkotlin/coroutines/CoroutineContext;

    move-result-object v0

    iget-object v10, v6, Lkotlinx/coroutines/DispatchedContinuation;->countOrElement:Ljava/lang/Object;

    .local v10, "countOrElement$iv$iv$iv":Ljava/lang/Object;
    move-object/from16 v20, v0

    .local v20, "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    const/16 v21, 0x0

    .line 532
    .local v21, "$i$f$withCoroutineContext":I
    move-object/from16 v1, v20

    .end local v20    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .local v1, "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    invoke-static {v1, v10}, Lkotlinx/coroutines/internal/ThreadContextKt;->updateThreadContext(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0
    :try_end_2
    .catchall {:try_start_2 .. :try_end_2} :catchall_4

    move-object/from16 v20, v0

    .line 533
    .local v20, "oldValue$iv$iv$iv":Ljava/lang/Object;
    nop

    .line 534
    const/4 v0, 0x0

    .line 535
    .local v0, "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatchedWithException$1$iv$iv":I
    move/from16 v22, v0

    .end local v0    # "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatchedWithException$1$iv$iv":I
    .local v22, "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatchedWithException$1$iv$iv":I
    :try_start_3
    iget-object v0, v6, Lkotlinx/coroutines/DispatchedContinuation;->continuation:Lkotlin/coroutines/Continuation;

    move-object/from16 v23, v8

    .local v0, "$this$resumeWithStackTrace$iv$iv$iv":Lkotlin/coroutines/Continuation;
    .local v23, "exception$iv$iv$iv":Ljava/lang/Throwable;
    const/16 v24, 0x0

    .line 536
    .local v24, "$i$f$resumeWithStackTrace":I
    sget-object v25, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_2

    move-object/from16 v25, v3

    move-object/from16 v3, v23

    .end local v23    # "exception$iv$iv$iv":Ljava/lang/Throwable;
    .local v3, "exception$iv$iv$iv":Ljava/lang/Throwable;
    .local v25, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :try_start_4
    invoke-static {v3, v0}, Lkotlinx/coroutines/internal/StackTraceRecoveryKt;->recoverStackTrace(Ljava/lang/Throwable;Lkotlin/coroutines/Continuation;)Ljava/lang/Throwable;

    move-result-object v23

    invoke-static/range {v23 .. v23}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v23

    move-object/from16 v26, v3

    .end local v3    # "exception$iv$iv$iv":Ljava/lang/Throwable;
    .local v26, "exception$iv$iv$iv":Ljava/lang/Throwable;
    invoke-static/range {v23 .. v23}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v3

    invoke-interface {v0, v3}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 537
    nop

    .line 538
    .end local v0    # "$this$resumeWithStackTrace$iv$iv$iv":Lkotlin/coroutines/Continuation;
    .end local v24    # "$i$f$resumeWithStackTrace":I
    .end local v26    # "exception$iv$iv$iv":Ljava/lang/Throwable;
    nop

    .end local v22    # "$i$a$-withCoroutineContext-DispatchedContinuation$resumeUndispatchedWithException$1$iv$iv":I
    sget-object v0, Lkotlin/Unit;->INSTANCE:Lkotlin/Unit;
    :try_end_4
    .catchall {:try_start_4 .. :try_end_4} :catchall_1

    .line 539
    move-object/from16 v3, v20

    .end local v20    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .local v3, "oldValue$iv$iv$iv":Ljava/lang/Object;
    :try_start_5
    invoke-static {v1, v3}, Lkotlinx/coroutines/internal/ThreadContextKt;->restoreThreadContext(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Object;)V

    .line 540
    .end local v1    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .end local v3    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .end local v10    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .end local v21    # "$i$f$withCoroutineContext":I
    goto :goto_2

    .line 539
    .restart local v1    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .restart local v10    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .restart local v20    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .restart local v21    # "$i$f$withCoroutineContext":I
    :catchall_1
    move-exception v0

    move-object/from16 v3, v20

    .end local v20    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .restart local v3    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    goto :goto_1

    .end local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .local v3, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v20    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    :catchall_2
    move-exception v0

    move-object/from16 v25, v3

    move-object/from16 v3, v20

    .end local v20    # "oldValue$iv$iv$iv":Ljava/lang/Object;
    .local v3, "oldValue$iv$iv$iv":Ljava/lang/Object;
    .restart local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_1
    invoke-static {v1, v3}, Lkotlinx/coroutines/internal/ThreadContextKt;->restoreThreadContext(Lkotlin/coroutines/CoroutineContext;Ljava/lang/Object;)V

    .end local v4    # "$i$f$resumeCancellableWithException":I
    .end local v5    # "context$iv":Lkotlin/coroutines/CoroutineContext;
    .end local v7    # "mode$iv$iv":I
    .end local v9    # "state$iv":Lkotlinx/coroutines/CompletedExceptionally;
    .end local v11    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v12    # "doYield$iv$iv":Z
    .end local v13    # "$i$f$executeUnconfined":I
    .end local v14    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .end local v15    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v16    # "$i$f$runUnconfinedEventLoop":I
    .end local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local p0    # "$this$resumeCancellableWithException":Lkotlin/coroutines/Continuation;
    .end local p1    # "exception":Ljava/lang/Throwable;
    throw v0

    .line 529
    .end local v1    # "context$iv$iv$iv":Lkotlin/coroutines/CoroutineContext;
    .end local v6    # "this_$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v8    # "exception$iv$iv":Ljava/lang/Throwable;
    .end local v10    # "countOrElement$iv$iv$iv":Ljava/lang/Object;
    .end local v18    # "$i$f$resumeUndispatchedWithException":I
    .end local v21    # "$i$f$withCoroutineContext":I
    .local v3, "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v4    # "$i$f$resumeCancellableWithException":I
    .restart local v5    # "context$iv":Lkotlin/coroutines/CoroutineContext;
    .restart local v7    # "mode$iv$iv":I
    .restart local v9    # "state$iv":Lkotlinx/coroutines/CompletedExceptionally;
    .restart local v11    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v12    # "doYield$iv$iv":Z
    .restart local v13    # "$i$f$executeUnconfined":I
    .restart local v14    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .restart local v15    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v16    # "$i$f$runUnconfinedEventLoop":I
    .restart local p0    # "$this$resumeCancellableWithException":Lkotlin/coroutines/Continuation;
    .restart local p1    # "exception":Ljava/lang/Throwable;
    :cond_3
    move-object/from16 v25, v3

    .line 541
    .end local v3    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_2
    nop

    .end local v17    # "$i$a$-executeUnconfined-DispatchedContinuation$resumeCancellableWithException$1$iv":I
    nop

    .line 542
    :goto_3
    nop

    .line 544
    invoke-virtual {v14}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v0
    :try_end_5
    .catchall {:try_start_5 .. :try_end_5} :catchall_3

    if-nez v0, :cond_4

    goto :goto_5

    .line 542
    :cond_4
    goto :goto_3

    .line 555
    :catchall_3
    move-exception v0

    goto :goto_4

    .end local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v3    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :catchall_4
    move-exception v0

    move-object/from16 v25, v3

    .line 560
    .end local v3    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .local v0, "e$iv$iv$iv":Ljava/lang/Throwable;
    .restart local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_4
    const/4 v1, 0x0

    :try_start_6
    invoke-virtual {v15, v0, v1}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_6
    .catchall {:try_start_6 .. :try_end_6} :catchall_5

    .line 553
    .end local v0    # "e$iv$iv$iv":Ljava/lang/Throwable;
    :goto_5
    const/4 v1, 0x1

    invoke-virtual {v14, v1}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    .line 554
    nop

    .line 564
    nop

    .line 565
    .end local v15    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v16    # "$i$f$runUnconfinedEventLoop":I
    nop

    .line 502
    .end local v7    # "mode$iv$iv":I
    .end local v11    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v12    # "doYield$iv$iv":Z
    .end local v13    # "$i$f$executeUnconfined":I
    .end local v14    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    :goto_6
    nop

    .line 566
    .end local v4    # "$i$f$resumeCancellableWithException":I
    .end local v5    # "context$iv":Lkotlin/coroutines/CoroutineContext;
    .end local v9    # "state$iv":Lkotlinx/coroutines/CompletedExceptionally;
    .end local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :goto_7
    nop

    .line 567
    goto :goto_8

    .line 554
    .restart local v4    # "$i$f$resumeCancellableWithException":I
    .restart local v5    # "context$iv":Lkotlin/coroutines/CoroutineContext;
    .restart local v7    # "mode$iv$iv":I
    .restart local v9    # "state$iv":Lkotlinx/coroutines/CompletedExceptionally;
    .restart local v11    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v12    # "doYield$iv$iv":Z
    .restart local v13    # "$i$f$executeUnconfined":I
    .restart local v14    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .restart local v15    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v16    # "$i$f$runUnconfinedEventLoop":I
    .restart local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :catchall_5
    move-exception v0

    move-object v1, v0

    .line 553
    const/4 v3, 0x1

    invoke-virtual {v14, v3}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    throw v1

    .line 190
    .end local v4    # "$i$f$resumeCancellableWithException":I
    .end local v5    # "context$iv":Lkotlin/coroutines/CoroutineContext;
    .end local v7    # "mode$iv$iv":I
    .end local v9    # "state$iv":Lkotlinx/coroutines/CompletedExceptionally;
    .end local v11    # "$this$executeUnconfined$iv$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v12    # "doYield$iv$iv":Z
    .end local v13    # "$i$f$executeUnconfined":I
    .end local v14    # "eventLoop$iv$iv":Lkotlinx/coroutines/EventLoop;
    .end local v15    # "$this$runUnconfinedEventLoop$iv$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v16    # "$i$f$runUnconfinedEventLoop":I
    .end local v25    # "this_$iv":Lkotlinx/coroutines/DispatchedContinuation;
    :cond_5
    move-object/from16 v0, p0

    .local v0, "$this$resumeWithStackTrace$iv":Lkotlin/coroutines/Continuation;
    const/4 v1, 0x0

    .line 568
    .local v1, "$i$f$resumeWithStackTrace":I
    sget-object v3, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {v2, v0}, Lkotlinx/coroutines/internal/StackTraceRecoveryKt;->recoverStackTrace(Ljava/lang/Throwable;Lkotlin/coroutines/Continuation;)Ljava/lang/Throwable;

    move-result-object v3

    invoke-static {v3}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v3

    invoke-static {v3}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v3

    invoke-interface {v0, v3}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 569
    nop

    .line 191
    .end local v0    # "$this$resumeWithStackTrace$iv":Lkotlin/coroutines/Continuation;
    .end local v1    # "$i$f$resumeWithStackTrace":I
    :goto_8
    return-void
.end method

.method public static final resumeDirect(Lkotlin/coroutines/Continuation;Ljava/lang/Object;)V
    .locals 2
    .param p0, "$this$resumeDirect"    # Lkotlin/coroutines/Continuation;
    .param p1, "value"    # Ljava/lang/Object;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlin/coroutines/Continuation<",
            "-TT;>;TT;)V"
        }
    .end annotation

    const-string v0, "$this$resumeDirect"

    invoke-static {p0, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 193
    nop

    .line 194
    instance-of v0, p0, Lkotlinx/coroutines/DispatchedContinuation;

    if-eqz v0, :cond_0

    move-object v0, p0

    check-cast v0, Lkotlinx/coroutines/DispatchedContinuation;

    iget-object v0, v0, Lkotlinx/coroutines/DispatchedContinuation;->continuation:Lkotlin/coroutines/Continuation;

    sget-object v1, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {p1}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v1

    invoke-interface {v0, v1}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    goto :goto_0

    .line 195
    :cond_0
    sget-object v0, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {p1}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v0

    invoke-interface {p0, v0}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 196
    :goto_0
    return-void
.end method

.method public static final resumeDirectWithException(Lkotlin/coroutines/Continuation;Ljava/lang/Throwable;)V
    .locals 3
    .param p0, "$this$resumeDirectWithException"    # Lkotlin/coroutines/Continuation;
    .param p1, "exception"    # Ljava/lang/Throwable;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lkotlin/coroutines/Continuation<",
            "-TT;>;",
            "Ljava/lang/Throwable;",
            ")V"
        }
    .end annotation

    const-string v0, "$this$resumeDirectWithException"

    invoke-static {p0, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v0, "exception"

    invoke-static {p1, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 198
    nop

    .line 199
    instance-of v0, p0, Lkotlinx/coroutines/DispatchedContinuation;

    if-eqz v0, :cond_0

    move-object v0, p0

    check-cast v0, Lkotlinx/coroutines/DispatchedContinuation;

    iget-object v0, v0, Lkotlinx/coroutines/DispatchedContinuation;->continuation:Lkotlin/coroutines/Continuation;

    .local v0, "$this$resumeWithStackTrace$iv":Lkotlin/coroutines/Continuation;
    const/4 v1, 0x0

    .line 570
    .local v1, "$i$f$resumeWithStackTrace":I
    sget-object v2, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {p1, v0}, Lkotlinx/coroutines/internal/StackTraceRecoveryKt;->recoverStackTrace(Ljava/lang/Throwable;Lkotlin/coroutines/Continuation;)Ljava/lang/Throwable;

    move-result-object v2

    invoke-static {v2}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v2

    invoke-static {v2}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v2

    invoke-interface {v0, v2}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 571
    .end local v0    # "$this$resumeWithStackTrace$iv":Lkotlin/coroutines/Continuation;
    .end local v1    # "$i$f$resumeWithStackTrace":I
    goto :goto_0

    .line 200
    :cond_0
    move-object v0, p0

    .restart local v0    # "$this$resumeWithStackTrace$iv":Lkotlin/coroutines/Continuation;
    const/4 v1, 0x0

    .line 572
    .restart local v1    # "$i$f$resumeWithStackTrace":I
    sget-object v2, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {p1, v0}, Lkotlinx/coroutines/internal/StackTraceRecoveryKt;->recoverStackTrace(Ljava/lang/Throwable;Lkotlin/coroutines/Continuation;)Ljava/lang/Throwable;

    move-result-object v2

    invoke-static {v2}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v2

    invoke-static {v2}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v2

    invoke-interface {v0, v2}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 573
    nop

    .line 201
    .end local v0    # "$this$resumeWithStackTrace$iv":Lkotlin/coroutines/Continuation;
    .end local v1    # "$i$f$resumeWithStackTrace":I
    :goto_0
    return-void
.end method

.method private static final resumeUnconfined(Lkotlinx/coroutines/DispatchedTask;)V
    .locals 7
    .param p0, "$this$resumeUnconfined"    # Lkotlinx/coroutines/DispatchedTask;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lkotlinx/coroutines/DispatchedTask<",
            "*>;)V"
        }
    .end annotation

    .line 42
    sget-object v0, Lkotlinx/coroutines/ThreadLocalEventLoop;->INSTANCE:Lkotlinx/coroutines/ThreadLocalEventLoop;

    invoke-virtual {v0}, Lkotlinx/coroutines/ThreadLocalEventLoop;->getEventLoop$kotlinx_coroutines_core()Lkotlinx/coroutines/EventLoop;

    move-result-object v0

    .line 43
    .local v0, "eventLoop":Lkotlinx/coroutines/EventLoop;
    invoke-virtual {v0}, Lkotlinx/coroutines/EventLoop;->isUnconfinedLoopActive()Z

    move-result v1

    if-eqz v1, :cond_0

    .line 45
    invoke-virtual {v0, p0}, Lkotlinx/coroutines/EventLoop;->dispatchUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    goto :goto_2

    .line 48
    :cond_0
    move-object v1, p0

    .local v1, "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    const/4 v2, 0x0

    .line 394
    .local v2, "$i$f$runUnconfinedEventLoop":I
    const/4 v3, 0x1

    invoke-virtual {v0, v3}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 395
    nop

    .line 396
    const/4 v4, 0x0

    .line 49
    .local v4, "$i$a$-runUnconfinedEventLoop-DispatchedKt$resumeUnconfined$1":I
    :try_start_0
    invoke-virtual {p0}, Lkotlinx/coroutines/DispatchedTask;->getDelegate$kotlinx_coroutines_core()Lkotlin/coroutines/Continuation;

    move-result-object v5

    const/4 v6, 0x3

    invoke-static {p0, v5, v6}, Lkotlinx/coroutines/DispatchedKt;->resume(Lkotlinx/coroutines/DispatchedTask;Lkotlin/coroutines/Continuation;I)V

    .line 50
    .end local v4    # "$i$a$-runUnconfinedEventLoop-DispatchedKt$resumeUnconfined$1":I
    nop

    .line 397
    :goto_0
    nop

    .line 399
    invoke-virtual {v0}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v4
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    if-nez v4, :cond_1

    goto :goto_1

    .line 397
    :cond_1
    goto :goto_0

    .line 410
    :catchall_0
    move-exception v4

    .line 415
    .local v4, "e$iv":Ljava/lang/Throwable;
    const/4 v5, 0x0

    :try_start_1
    invoke-virtual {v1, v4, v5}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_1

    .line 408
    .end local v4    # "e$iv":Ljava/lang/Throwable;
    :goto_1
    invoke-virtual {v0, v3}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    .line 409
    nop

    .line 419
    nop

    .line 51
    .end local v1    # "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v2    # "$i$f$runUnconfinedEventLoop":I
    :goto_2
    nop

    .line 52
    return-void

    .line 409
    .restart local v1    # "$this$runUnconfinedEventLoop$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v2    # "$i$f$runUnconfinedEventLoop":I
    :catchall_1
    move-exception v4

    .line 408
    invoke-virtual {v0, v3}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    throw v4
.end method

.method public static final resumeWithStackTrace(Lkotlin/coroutines/Continuation;Ljava/lang/Throwable;)V
    .locals 2
    .param p0, "$this$resumeWithStackTrace"    # Lkotlin/coroutines/Continuation;
    .param p1, "exception"    # Ljava/lang/Throwable;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lkotlin/coroutines/Continuation<",
            "*>;",
            "Ljava/lang/Throwable;",
            ")V"
        }
    .end annotation

    const/4 v0, 0x0

    .local v0, "$i$f$resumeWithStackTrace":I
    const-string v1, "$this$resumeWithStackTrace"

    invoke-static {p0, v1}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    const-string v1, "exception"

    invoke-static {p1, v1}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 326
    sget-object v1, Lkotlin/Result;->Companion:Lkotlin/Result$Companion;

    invoke-static {p1, p0}, Lkotlinx/coroutines/internal/StackTraceRecoveryKt;->recoverStackTrace(Ljava/lang/Throwable;Lkotlin/coroutines/Continuation;)Ljava/lang/Throwable;

    move-result-object v1

    invoke-static {v1}, Lkotlin/ResultKt;->createFailure(Ljava/lang/Throwable;)Ljava/lang/Object;

    move-result-object v1

    invoke-static {v1}, Lkotlin/Result;->constructor-impl(Ljava/lang/Object;)Ljava/lang/Object;

    move-result-object v1

    invoke-interface {p0, v1}, Lkotlin/coroutines/Continuation;->resumeWith(Ljava/lang/Object;)V

    .line 327
    return-void
.end method

.method private static final runUnconfinedEventLoop(Lkotlinx/coroutines/DispatchedTask;Lkotlinx/coroutines/EventLoop;Lkotlin/jvm/functions/Function0;)V
    .locals 4
    .param p0, "$this$runUnconfinedEventLoop"    # Lkotlinx/coroutines/DispatchedTask;
    .param p1, "eventLoop"    # Lkotlinx/coroutines/EventLoop;
    .param p2, "block"    # Lkotlin/jvm/functions/Function0;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lkotlinx/coroutines/DispatchedTask<",
            "*>;",
            "Lkotlinx/coroutines/EventLoop;",
            "Lkotlin/jvm/functions/Function0<",
            "Lkotlin/Unit;",
            ">;)V"
        }
    .end annotation

    const/4 v0, 0x0

    .line 58
    .local v0, "$i$f$runUnconfinedEventLoop":I
    const/4 v1, 0x1

    invoke-virtual {p1, v1}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 59
    nop

    .line 60
    :try_start_0
    invoke-interface {p2}, Lkotlin/jvm/functions/Function0;->invoke()Ljava/lang/Object;

    .line 61
    :goto_0
    nop

    .line 63
    invoke-virtual {p1}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v2
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    if-nez v2, :cond_0

    .line 61
    invoke-static {v1}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    goto :goto_1

    :cond_0
    goto :goto_0

    .line 65
    :catchall_0
    move-exception v2

    .line 70
    .local v2, "e":Ljava/lang/Throwable;
    const/4 v3, 0x0

    :try_start_1
    invoke-virtual {p0, v2, v3}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_1

    .end local v2    # "e":Ljava/lang/Throwable;
    invoke-static {v1}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    .line 72
    :goto_1
    invoke-virtual {p1, v1}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    invoke-static {v1}, Lkotlin/jvm/internal/InlineMarker;->finallyEnd(I)V

    .line 73
    nop

    .line 74
    return-void

    .line 73
    :catchall_1
    move-exception v2

    invoke-static {v1}, Lkotlin/jvm/internal/InlineMarker;->finallyStart(I)V

    .line 72
    invoke-virtual {p1, v1}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    invoke-static {v1}, Lkotlin/jvm/internal/InlineMarker;->finallyEnd(I)V

    throw v2
.end method

.method public static final yieldUndispatched(Lkotlinx/coroutines/DispatchedContinuation;)Z
    .locals 12
    .param p0, "$this$yieldUndispatched"    # Lkotlinx/coroutines/DispatchedContinuation;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Lkotlinx/coroutines/DispatchedContinuation<",
            "-",
            "Lkotlin/Unit;",
            ">;)Z"
        }
    .end annotation

    const-string v0, "$this$yieldUndispatched"

    invoke-static {p0, v0}, Lkotlin/jvm/internal/Intrinsics;->checkParameterIsNotNull(Ljava/lang/Object;Ljava/lang/String;)V

    .line 285
    sget-object v0, Lkotlin/Unit;->INSTANCE:Lkotlin/Unit;

    .local v0, "contState$iv":Ljava/lang/Object;
    const/4 v1, 0x1

    .local v1, "mode$iv":I
    const/4 v2, 0x1

    .local v2, "doYield$iv":Z
    move-object v3, p0

    .local v3, "$this$executeUnconfined$iv":Lkotlinx/coroutines/DispatchedContinuation;
    const/4 v4, 0x0

    .line 574
    .local v4, "$i$f$executeUnconfined":I
    sget-object v5, Lkotlinx/coroutines/ThreadLocalEventLoop;->INSTANCE:Lkotlinx/coroutines/ThreadLocalEventLoop;

    invoke-virtual {v5}, Lkotlinx/coroutines/ThreadLocalEventLoop;->getEventLoop$kotlinx_coroutines_core()Lkotlinx/coroutines/EventLoop;

    move-result-object v5

    .line 576
    .local v5, "eventLoop$iv":Lkotlinx/coroutines/EventLoop;
    invoke-virtual {v5}, Lkotlinx/coroutines/EventLoop;->isUnconfinedQueueEmpty()Z

    move-result v6

    const/4 v7, 0x0

    if-eqz v6, :cond_0

    goto :goto_3

    .line 577
    :cond_0
    invoke-virtual {v5}, Lkotlinx/coroutines/EventLoop;->isUnconfinedLoopActive()Z

    move-result v6

    const/4 v8, 0x1

    if-eqz v6, :cond_1

    .line 579
    iput-object v0, v3, Lkotlinx/coroutines/DispatchedContinuation;->_state:Ljava/lang/Object;

    .line 580
    iput v1, v3, Lkotlinx/coroutines/DispatchedContinuation;->resumeMode:I

    .line 581
    move-object v6, v3

    check-cast v6, Lkotlinx/coroutines/DispatchedTask;

    invoke-virtual {v5, v6}, Lkotlinx/coroutines/EventLoop;->dispatchUnconfined(Lkotlinx/coroutines/DispatchedTask;)V

    .line 582
    const/4 v7, 0x1

    goto :goto_2

    .line 585
    :cond_1
    move-object v6, v3

    check-cast v6, Lkotlinx/coroutines/DispatchedTask;

    .local v6, "$this$runUnconfinedEventLoop$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    const/4 v9, 0x0

    .line 586
    .local v9, "$i$f$runUnconfinedEventLoop":I
    invoke-virtual {v5, v8}, Lkotlinx/coroutines/EventLoop;->incrementUseCount(Z)V

    .line 587
    nop

    .line 588
    const/4 v10, 0x0

    .line 286
    .local v10, "$i$a$-executeUnconfined-DispatchedKt$yieldUndispatched$1":I
    :try_start_0
    invoke-virtual {p0}, Lkotlinx/coroutines/DispatchedContinuation;->run()V

    .line 287
    .end local v10    # "$i$a$-executeUnconfined-DispatchedKt$yieldUndispatched$1":I
    nop

    .line 589
    :goto_0
    nop

    .line 591
    invoke-virtual {v5}, Lkotlinx/coroutines/EventLoop;->processUnconfinedEvent()Z

    move-result v10
    :try_end_0
    .catchall {:try_start_0 .. :try_end_0} :catchall_0

    if-nez v10, :cond_2

    goto :goto_1

    .line 589
    :cond_2
    goto :goto_0

    .line 602
    :catchall_0
    move-exception v10

    .line 607
    .local v10, "e$iv$iv":Ljava/lang/Throwable;
    const/4 v11, 0x0

    :try_start_1
    invoke-virtual {v6, v10, v11}, Lkotlinx/coroutines/DispatchedTask;->handleFatalException$kotlinx_coroutines_core(Ljava/lang/Throwable;Ljava/lang/Throwable;)V
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_1

    .line 600
    .end local v10    # "e$iv$iv":Ljava/lang/Throwable;
    :goto_1
    invoke-virtual {v5, v8}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    .line 601
    nop

    .line 611
    nop

    .line 612
    .end local v6    # "$this$runUnconfinedEventLoop$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .end local v9    # "$i$f$runUnconfinedEventLoop":I
    nop

    .line 577
    :goto_2
    nop

    .line 287
    .end local v0    # "contState$iv":Ljava/lang/Object;
    .end local v1    # "mode$iv":I
    .end local v2    # "doYield$iv":Z
    .end local v3    # "$this$executeUnconfined$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .end local v4    # "$i$f$executeUnconfined":I
    .end local v5    # "eventLoop$iv":Lkotlinx/coroutines/EventLoop;
    :goto_3
    return v7

    .line 601
    .restart local v0    # "contState$iv":Ljava/lang/Object;
    .restart local v1    # "mode$iv":I
    .restart local v2    # "doYield$iv":Z
    .restart local v3    # "$this$executeUnconfined$iv":Lkotlinx/coroutines/DispatchedContinuation;
    .restart local v4    # "$i$f$executeUnconfined":I
    .restart local v5    # "eventLoop$iv":Lkotlinx/coroutines/EventLoop;
    .restart local v6    # "$this$runUnconfinedEventLoop$iv$iv":Lkotlinx/coroutines/DispatchedTask;
    .restart local v9    # "$i$f$runUnconfinedEventLoop":I
    :catchall_1
    move-exception v7

    .line 600
    invoke-virtual {v5, v8}, Lkotlinx/coroutines/EventLoop;->decrementUseCount(Z)V

    throw v7
.end method
